version: "3.9"

services:
  backend:
    build: .
    container_name: backend_service
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    command: ["node", "server.js"]

  redis:
    image: redis:7-alpine
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
