name: Keep Render Backend Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # allows manual trigger from GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Backend Awake
        run: |
          echo "Pinging Render backend to prevent sleep..."
          curl -s -o /dev/null -w "%{http_code}\n" https://rankbaaz.onrender.com || true
